const dishes = [
    {keyword: 'gazpacho', 
        name: 'Гаспачо', 
        price: 195, 
        category: 'soup', 
        count: '350 г', image: 'gazpacho.jpg', kind: "vegie"},
    {keyword: 'chicken', 
        name: 'Куриный суп', 
        price: 330, 
        category: 'soup', 
        count: '350 г', image: 'chicken.jpg', kind: "meat"},
    {keyword: 'mushroom_soup', 
        name: 'Грибной суп-пюре', 
        price: 185, 
        category: 'soup', 
        count: '330 г', image: 'mushroom_soup.jpg', kind: "vegie"},
    {keyword: 'norwegian_soup', 
        name: 'Норвежский суп', 
        price: 270, 
        category: 'soup', 
        count: '330 г', image: 'norwegian_soup.jpg', kind: "fish"},
    {keyword: 'ramen', 
        name: 'Рамен', 
        price: 375, 
        category: 'soup', 
        count: '425 г', image: 'ramen.jpg', kind: "meat"},
    {keyword: 'tomyum', 
        name: 'Том ям с креветками', 
        price: 650, 
        category: 'soup', 
        count: '500 г', image: 'tomyum.jpg', kind: "fish"},
    {keyword: 'caeser', 
        name: 'Цезарь с цыпленком', 
        price: 370, 
        category: 'salad', 
        count: '220 г', image: 'caesar.jpg', kind: "meat"},
    {keyword: 'caprese', 
        name: 'Капрезе с моцареллой', 
        price: 350, 
        category: 'salad', 
        count: '235 г', 
        image: 'caprese.jpg', kind: "vegie"},
    {keyword: 'frenchfries1', 
        name: 'Картофель фри с соусом Цезарь', 
        price: 280, 
        category: 'salad', 
        count: '235 г', 
        image: 'frenchfries1.jpg', kind: "vegie"},
    {keyword: 'frenchfries2', 
        name: 'Картофель фри с кетчупом', 
        price: 260, 
        category: 'salad', 
        count: '235 г', 
        image: 'frenchfries2.jpg', kind: "vegie"},
    {keyword: 'saladwithegg', 
        name: 'Корейский салат с овощами и яйцом', 
        price: 330, 
        category: 'salad', 
        count: '250 г', 
        image: 'saladwithegg.jpg', kind: "vegie"},
    {keyword: 'tunasalad', 
        name: 'Салат с тунцом', 
        price: 480, 
        category: 'salad', 
        count: '250 г', 
        image: 'tunasalad.jpg', kind: "fish"},
    {keyword: 'chickencutletsandmashedpotatoes', 
        name: 'Котлеты из курицы с картофельным пюре', 
        price: 225, 
        category: 'main', 
        count: '280 г', 
        image: 'chickencutletsandmashedpotatoes.jpg', 
        kind: "meat"},
    {keyword: 'fishrice', 
        name: 'Рыбная котлета с рисом и спаржей', 
        price: 320, 
        category: 'main', 
        count: '270 г', image: 'fishrice.jpg', kind: "fish"},
    {keyword: 'friedpotatoeswithmushrooms1', 
        name: 'Жаренкая картошка с грибами', 
        price: 150, 
        category: 'main', 
        count: '250 г', 
        image: 'friedpotatoeswithmushrooms1.jpg', 
        kind: "vegie"},
    {keyword: 'lasagna', 
        name: 'Лазанья', 
        price: 385, 
        category: 'main', 
        count: '310 г', image: 'lasagna.jpg', kind: "meat"},
    {keyword: 'pizza', 
        name: 'Пицца Маргарита', 
        price: 450, 
        category: 'main',
        count: '470 г', 
        image: 'pizza.jpg', kind: "vegie"},
    {keyword: 'shrimppasta', 
        name: 'Паста с креветками', 
        price: 340, 
        category: 'main', 
        count: '280 г', 
        image: 'shrimppasta.jpg', kind: "fish"},
    {keyword: 'applejuice', 
        name: 'Яблочный сок', 
        price: 90, 
        category: 'drink', 
        count: '300 мл', image: 'applejuice.jpg', kind: "cold"},
    {keyword: 'cappuccino', 
        name: 'Капучино', 
        price: 180, 
        category: 'drink', 
        count: '300 мл', image: 'cappuccino.jpg', kind: "hot"},
    {keyword: 'carrotjuice', 
        name: 'Морковный сок', 
        price: 110, 
        category: 'drink', 
        count: '300 мл', image: 'carrotjuice.jpg', kind: "cold"},
    {keyword: 'greentea', 
        name: 'Зеленый чай', 
        price: 100, 
        category: 'drink', 
        count: '300 мл', image: 'greentea.jpg', kind: "hot"},
    {keyword: 'orangejuice', 
        name: 'Апельсиновый сок', 
        price: 120, 
        category: 'drink', 
        count: '300 мл', image: 'orangejuice.jpg', kind: "cold"},
    {keyword: 'tea', 
        name: 'Черный чай', 
        price: 90, 
        category: 'drink', 
        count: '300 мл', image: 'tea.jpg', kind: "hot"},
    {keyword: 'baklava', 
        name: 'Пахлава', 
        price: 220, 
        category: 'desert', 
        count: '300 г', image: 'baklava.jpg', kind: "little"},
    {keyword: 'cheesecake', 
        name: 'Чизкейк', 
        price: 240, 
        category: 'desert', 
        count: '125 г', 
        image: 'checheesecake.jpg', kind: "little"},
    {keyword: 'chocolatecake', 
        name: 'Шоколадный торт', 
        price: 270, 
        category: 'desert', 
        count: '140 г', image: 'chocolatecake.jpg', kind: "mid"},
    {keyword: 'chocolatecheesecake', 
        name: 'Шоколадный чизкейк', 
        price: 260, 
        category: 'desert', 
        count: '125 г', 
        image: 'chocolatecheesecake.jpg', kind: "little"},
    {keyword: 'donuts6pc', 
        name: 'Пончики (6 штуки)', 
        price: 650, 
        category: 'desert', 
        count: '350 г', image: 'donuts.jpg', kind: "mid"},
    {keyword: 'donuts3pc', 
        name: 'Пончики (3 штук)', 
        price: 410, 
        category: 'desert', 
        count: '700 г', image: 'donuts2.jpg', kind: "large"},
];
